
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 525092
	#The name of the modpack
	modpackName = "Whimsyhell"
	#The version of the modpack
	modpackVersion = "1.20.1_4"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

