#Disable wool drops to force the player to get shears.
disableWoolDrops = true
#Use skill fragments as the way of leveling up skills instead of XP levels.
useSkillFragments = false
#This makes it so that when you level up from a higher level, no more XP points will be consumed than when leveling up from a lower level
useXpPoints = false
#The minimum amount of skill levels lost on death.
#Range: 0 ~ 100
deathLevelLossMin = 0
#The maximum amount of skill levels lost on death.
#Range: 0 ~ 100
deathLevelLossMax = 0
#Amount of skill fragments obtained by completing task advancements.
#Range: 0 ~ 64
skillFragmentsFromTasks = 1
#Amount of skill fragments obtained by completing goal advancements.
#Range: 0 ~ 64
skillFragmentsFromGoals = 2
#Amount of skill fragments obtained by completing challenge advancements.
#Range: 0 ~ 64
skillFragmentsFromChallenges = 3
#Starting cost of upgrading to level 2, in levels.
#Range: 0 ~ 10
startingCost = 2
#Amount of levels added to the cost with each upgrade (use 0 for constant cost).
#Range: 0 ~ 10
costIncrease = 1
#Maximum level each skill can be upgraded to.
#Range: 2 ~ 100
maximumLevel = 32
#List of item and block skill requirements.
#Format: mod:id skill:level
#Valid skills: attack, defence/defense, mining, gathering, farming, building, agility, magic
skillLocks = [
    "apotheosis:library magic:15", 
    "apotheosis:potion_charm attack:15 defense:15 agility:15 magic:15",
    "apotheosis:reforging_table building:15 gathering:15", 
    "apotheosis:salvaging_table building:10 magic:10", 
    "ars_elemental:air_bangle magic:10",
    "ars_elemental:air_focus magic:10",
    "ars_elemental:base_bangle magic:10",
    "ars_elemental:curio_bag magic:10",
    "ars_elemental:earth_bangle magic:10",
    "ars_elemental:earth_focus magic:10",
    "ars_elemental:fire_bangle magic:10",
    "ars_elemental:fire_focus magic:10",
    "ars_elemental:lesser_air_focus magic:10",
    "ars_elemental:lesser_earth_focus magic:10",
    "ars_elemental:lesser_fire_focus magic:10",
    "ars_elemental:lesser_water_focus magic:10",
    "ars_elemental:necrotic_focus magic:10",
    "ars_elemental:water_bangle magic:10",
    "ars_elemental:water_focus magic:10",
    "ars_nouveau:amulet_of_mana_boost magic:10",
    "ars_nouveau:amulet_of_mana_regen magic:10",
    "ars_nouveau:apprentice_spell_book magic:7", 
    "ars_nouveau:archmage_spell_book magic:15", 
    "ars_nouveau:belt_of_levitation magic:10",
    "ars_nouveau:belt_of_unstable_gifts magic:10",
    "ars_nouveau:novice_spell_book magic:5",
    "ars_nouveau:ring_of_greater_discount magic:10",
    "ars_nouveau:ring_of_lesser_discount magic:10",
    "ars_nouveau:scribes_table magic:5",
    "ars_nouveau:shapers_focus magic:10",
    "ars_nouveau:source_jar magic:5",
    "ars_nouveau:summon_focus magic:10",
    "artifacts:antidote_vessel defense:10",
    "artifacts:aqua_dashers agility:10",
    "artifacts:bunny_hoppers agility:10",
    "artifacts:charm_of_sinking agility:10",
    "artifacts:cloud_in_a_bottle agility:10",
    "artifacts:cross_necklace defense:10",
    "artifacts:crystal_heart defense:10",
    "artifacts:digging_claws gathering:10",
    "artifacts:feral_claws attack:10",
    "artifacts:fire_gauntlet attack:10",
    "artifacts:flame_pendant attack:10",
    "artifacts:flippers agility:10",
    "artifacts:golden_hook agility:10 attack:10 magic:10",
    "artifacts:helium_flamingo agility:10",
    "artifacts:kitty_slippers agility:10",
    "artifacts:lucky_scarf magic:10",
    "artifacts:night_vision_goggles attack:10 defense:10",
    "artifacts:novelty_drinking_hat gathering:2",
    "artifacts:obsidian_skull defense:10",
    "artifacts:panic_necklace agility:10",
    "artifacts:plastic_drinking_hat gathering:10",
    "artifacts:pocket_piston attack:10",
    "artifacts:power_glove attack:10",
    "artifacts:running_shoes agility:10",
    "artifacts:scarf_of_invisibility defense:10 magic:10",
    "artifacts:shock_pendant attack:10 magic:10",
    "artifacts:snorkel agility:10",
    "artifacts:steadfast_spikes agility:10",
    "artifacts:superstitious_hat magic:10",
    "artifacts:thorn_pendant attack:10",
    "artifacts:universal_attractor gathering:10",
    "artifacts:vampiric_glove attack:10 defense:10",
    "artifacts:villager_hat gathering:10",
    "artifacts:whoopee_cushion agility:2",
    "betteranimalsplus:bear_cape_black agility:2",
    "betteranimalsplus:bear_cape_brown agility:2",
    "betteranimalsplus:bear_cape_kermode agility:2",
    "betteranimalsplus:wolf_cape_arctic agility:2",
    "betteranimalsplus:wolf_cape_black agility:2",
    "betteranimalsplus:wolf_cape_brown agility:2",
    "betteranimalsplus:wolf_cape_classic agility:2",
    "betteranimalsplus:wolf_cape_red agility:2",
    "betteranimalsplus:wolf_cape_timber agility:2",
    "botania:aura_ring magic:10",
    "botania:aura_ring_greater magic:10",
    "botania:balance_cloak magic:10",
    "botania:blood_pendant magic:10",
    "botania:cloud_pendant magic:10",
    "botania:cosmetic_alien_antenna magic:10",
    "botania:cosmetic_anaglyph_glasses magic:10",
    "botania:cosmetic_ancient_mask magic:10",
    "botania:cosmetic_black_bowtie magic:10",
    "botania:cosmetic_black_tie magic:10",
    "botania:cosmetic_blue_butterfly magic:10",
    "botania:cosmetic_botanist_emblem magic:10",
    "botania:cosmetic_cat_ears magic:10",
    "botania:cosmetic_clock_eye magic:10",
    "botania:cosmetic_devil_horns magic:10",
    "botania:cosmetic_devil_tail magic:10",
    "botania:cosmetic_eerie_mask magic:10",
    "botania:cosmetic_engineer_goggles magic:10",
    "botania:cosmetic_eyepatch magic:10",
    "botania:cosmetic_four_leaf_clover magic:10",
    "botania:cosmetic_googly_eyes magic:10",
    "botania:cosmetic_groucho_glasses magic:10",
    "botania:cosmetic_hyper_plus magic:10",
    "botania:cosmetic_kamui_eye magic:10",
    "botania:cosmetic_lusitanic_shield magic:10",
    "botania:cosmetic_orange_shades magic:10",
    "botania:cosmetic_pink_flower_bud magic:10",
    "botania:cosmetic_polka_dotted_bows magic:10",
    "botania:cosmetic_puffy_scarf magic:10",
    "botania:cosmetic_questgiver_mark magic:10",
    "botania:cosmetic_red_glasses magic:10",
    "botania:cosmetic_red_ribbons magic:10",
    "botania:cosmetic_thick_eyebrows magic:10",
    "botania:cosmetic_thinking_hand magic:10",
    "botania:cosmetic_tiny_potato_mask magic:10",
    "botania:cosmetic_unicorn_horn magic:10",
    "botania:cosmetic_wicked_eyepatch magic:10",
    "botania:cosmetic_witch_pin magic:10",
    "botania:diva_charm magic:10",
    "botania:dodge_ring magic:10",
    "botania:flight_tiara magic:10",
    "botania:goddess_charm magic:10",
    "botania:holy_cloak magic:10",
    "botania:ice_pendant magic:10",
    "botania:invisibility_cloak magic:10",
    "botania:itemfinder magic:10",
    "botania:knockback_belt magic:10",
    "botania:lava_pendant magic:10",
    "botania:loki_ring magic:10",
    "botania:magnet_ring magic:10",
    "botania:magnet_ring_greater magic:10",
    "botania:mana_ring magic:10",
    "botania:mana_ring_greater magic:10",
    "botania:mining_ring magic:10",
    "botania:monocle magic:10",
    "botania:odin_ring magic:10",
    "botania:pixie_ring magic:10",
    "botania:reach_ring magic:10",
    "botania:speed_up_belt magic:10",
    "botania:super_cloud_pendant magic:10",
    "botania:super_lava_pendant magic:10",
    "botania:super_travel_belt magic:10",
    "botania:swap_ring magic:10",
    "botania:third_eye magic:10",
    "botania:thor_ring magic:10",
    "botania:tiny_planet magic:10",
    "botania:travel_belt magic:10",
    "botania:unholy_cloak magic:10",
    "botania:water_ring magic:10",
    "byg:ametrine_boots defence:10", 
    "byg:ametrine_chestplate defence:10", 
    "byg:ametrine_helmet defence:10", 
    "byg:ametrine_leggings defence:10", 
    "byg:pendorite_axe gathering:10", 
    "byg:pendorite_battleaxe attack:10 gathering:10", 
    "byg:pendorite_hoe farming:10", 
    "byg:pendorite_pickaxe mining:10", 
    "byg:pendorite_shovel gathering:10", 
    "byg:pendorite_sword attack:10", 
    "create:goggles building:5",
    "cyclic:antigravity attack:15 defense:15 agility:15 magic:15",
    "cyclic:anvil building:10", 
    "cyclic:charm_antidote attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_antipotion attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_attack_speed attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_boostpotion attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_creeper attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_crit attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_fire attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_invisible attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_knockback_resistance attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_longfall attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_luck attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_magicdefense attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_speed attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_starvation attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_stealthpotion attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_stone attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_torch attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_torch_cave attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_ultimate attack:25 defense:25 agility:25 magic:25",
    "cyclic:charm_venom attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_void attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_water attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_wing attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_wither attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_xp_blocker attack:15 defense:15 agility:15 magic:15",
    "cyclic:charm_xp_speed attack:15 defense:15 agility:15 magic:15",
    "cyclic:disenchanter magic:15", 
    "cyclic:flippers agility:15 magic:15",
    "cyclic:glove_climb agility:15 magic:15",
    "cyclic:glowing_helmet agility:15 magic:15",
    "cyclic:melter building:10",
    "cyclic:quiver_damage attack:15 defense:15 agility:15 magic:15",
    "cyclic:quiver_lightning attack:15 defense:15 agility:15 magic:15",
    "cyclic:solidifier building:10",
    "cyclic:soulstone attack:25 defense:25 agility:25 magic:25",
    "dragonmounts:dragon_egg farming:15 agility:20", 
    "forbidden_arcanus:hephaestus_forge building:15 gathering:15 magic:15",
    "mekanism:digital_miner building:32 mining:32", 
    "mekanism:metallurgic_infuser building:5", 
    "mekanism:qio_drive_array building:32", 
    "mekanism:quantum_entangloporter building:15", 
    "minecraft:anvil building:5", 
    "minecraft:bow attack:5 agility:3", 
    "minecraft:bundle gathering:5",
    "minecraft:chipped_anvil building:5", 
    "minecraft:crossbow attack:5 agility:5", 
    "minecraft:damaged_anvil building:5", 
    "minecraft:diamond_axe gathering:15", 
    "minecraft:diamond_boots defence:15", 
    "minecraft:diamond_chestplate defence:15", 
    "minecraft:diamond_helmet defence:15", 
    "minecraft:diamond_hoe farming:15", 
    "minecraft:diamond_leggings defence:15", 
    "minecraft:diamond_pickaxe mining:15", 
    "minecraft:diamond_shovel gathering:15", 
    "minecraft:diamond_sword attack:15", 
    "minecraft:donkey agility:5", 
    "minecraft:elytra agility:20", 
    "minecraft:enchanted_golden_apple magic:10", 
    "minecraft:enchanting_table magic:10", 
    "minecraft:end_crystal magic:20", 
    "minecraft:ender_chest magic:15", 
    "minecraft:ender_eye magic:10", 
    "minecraft:ender_pearl magic:5", 
    "minecraft:fishing_rod gathering:5", 
    "minecraft:golden_apple magic:5", 
    "minecraft:horse agility:5", 
    "minecraft:iron_axe gathering:5", 
    "minecraft:iron_boots defence:5", 
    "minecraft:iron_chestplate defence:5", 
    "minecraft:iron_helmet defence:5", 
    "minecraft:iron_hoe farming:5", 
    "minecraft:iron_leggings defence:5", 
    "minecraft:iron_pickaxe mining:5", 
    "minecraft:iron_shovel gathering:5", 
    "minecraft:iron_sword attack:5", 
    "minecraft:lead farming:5", 
    "minecraft:minecart agility:10", 
    "minecraft:mule agility:5", 
    "minecraft:netherite_axe gathering:30", 
    "minecraft:netherite_boots defence:30", 
    "minecraft:netherite_chestplate defence:30", 
    "minecraft:netherite_helmet defence:30", 
    "minecraft:netherite_hoe farming:30", 
    "minecraft:netherite_leggings defence:30", 
    "minecraft:netherite_pickaxe mining:30", 
    "minecraft:netherite_shovel gathering:30", 
    "minecraft:netherite_sword attack:30", 
    "minecraft:piston building:5", 
    "minecraft:shears gathering:5", 
    "minecraft:shield defence:5", 
    "minecraft:smithing_table building:10", 
    "minecraft:sticky_piston building:10", 
    "minecraft:stone_axe gathering:3", 
    "minecraft:stone_hoe farming:3", 
    "minecraft:stone_pickaxe mining:3", 
    "minecraft:stone_shovel gathering:3", 
    "minecraft:stone_sword attack:3", 
    "minecraft:strider agility:10",
    "minecraft:tnt building:5", 
    "minecraft:totem_of_undying defense:10",
    "minecraft:trident attack:15 agility:10", 
    "minecraft:turtle_helmet defence:10", 
    "minecraft:wood_axe gathering:2", 
    "minecraft:wood_hoe farming:2", 
    "minecraft:wood_pickaxe mining:2", 
    "minecraft:wood_shovel gathering:2", 
    "minecraft:wood_sword attack:2", 
    "mysticalagriculture:creative_soulium_dagger attack:15 gathering:15 magic:15", 
    "rebornstorage:creative_super_wireless_crafting_grid building:10 gathering:10",
    "rebornstorage:super_wireless_crafting_grid building:10 gathering:10",
    "refinedstorage:controller building:7", 
    "refinedstorage:creative_wireless_crafting_monitor building:10 gathering:10",
    "refinedstorage:creative_wireless_fluid_grid building:10 gathering:10",
    "refinedstorage:creative_wireless_grid building:10 gathering:10",
    "refinedstorage:wireless_crafting_monitor building:10 gathering:10",
    "refinedstorage:wireless_fluid_grid building:10 gathering:10",
    "refinedstorage:wireless_grid building:10 gathering:10",
    "refinedstorageaddons:creative_wireless_crafting_grid building:10 gathering:10",
    "refinedstorageaddons:wireless_crafting_grid building:10 gathering:10",
    "silentgear:axe gathering:15", 
    "silentgear:boots defence:15", 
    "silentgear:bow attack:15 agility:15", 
    "silentgear:bracelet attack:15 defense:15",
    "silentgear:chestplate defence:15", 
    "silentgear:crossbow attack:15 agility:15", 
    "silentgear:dagger attack:15", 
    "silentgear:elytra agility:25",
    "silentgear:excavator gathering:15", 
    "silentgear:hammer mining:15", 
    "silentgear:helmet defence:15", 
    "silentgear:katana attack:15", 
    "silentgear:leggings defence:15", 
    "silentgear:machete attack:15 gathering:15", 
    "silentgear:material_grader building:10", "silentgear:salvager building:5", 
    "silentgear:mattock gathering:15 farming:15", 
    "silentgear:paxel mining:15 gathering:15", 
    "silentgear:pickaxe mining:15", 
    "silentgear:prospector_hammer mining:15", 
    "silentgear:ring attack:15 defense:15",
    "silentgear:saw gathering:15", 
    "silentgear:shovel gathering:15", 
    "silentgear:sword attack:15", 
    "sophisticatedbackpacks:backpack gathering:5",
    "sophisticatedbackpacks:diamond_backpack gathering:5",
    "sophisticatedbackpacks:gold_backpack gathering:5",
    "sophisticatedbackpacks:iron_backpack gathering:5",
    "sophisticatedbackpacks:netherite_backpack gathering:5",
    "thermal:fluid_reservoir building:10 gathering:10",
    "thermal:flux_capacitor building:10 gathering:10",
    "thermal:flux_magnet building:10 gathering:10",
    "thermal:potion_infuser building:10 agility:10",
    "thermal:potion_quiver building:10 agility:10",
    "thermal:satchel building:10 agility:10",
    "toolbelt:belt agility:7 building:7 gathering:7",
    "torchmaster:megatorch building:10 defense:10",
    "twilightforest:charm_of_keeping_1 attack:7 agility:7 magic:7",
    "twilightforest:charm_of_keeping_2 attack:7 agility:7 magic:7",
    "twilightforest:charm_of_keeping_3 attack:7 agility:7 magic:7",
    "twilightforest:charm_of_life_1 attack:7 defense:7 magic:7",
    "twilightforest:charm_of_life_2 attack:7 defense:7 magic:7",
    "twilightforest:uncrafting_table building:20 gathering:20 magic:20"
]
