
#With default value every difficulty perk maxes out at difficulty 250
[general]
	#Disable/Enables the whole difficulty scaling of this mod. Requires a mc restart
	"Enable difficulty scaling" = true
	#Time in ticks for which the difficulty shouldnt increase at the beginning. One full minecraft day is 24000 ticks
	#Range: > 0
	"Difficulty Delay" = 0
	#Handles increase in difficulty regarding current difficulty.
	#Format is <minimum current difficulty>-<increase every 2400 ticks>
	#Example ["0-0.01","10-0.1","30-0"]
	#So the difficulty increases by 0.01 every 2400 ticks (->0.1 per mc day) till it reaches a difficulty of 10.
	#Then it increases by 1 per mc day till it reaches 30 and then stops.
	"Difficulty Increase" = ["0-0.1", "100-0.25", "250-0.5", "500-0.75", "1000-0"]
	#Wether difficulty should only increase with at least one online players or not
	"Ignore Players" = false
	#Should punish time skipping with e.g. bed, commands? If false, difficulty will increase by 0.1 regardless of skipped time.
	"Punish Time Skip" = true
	#Disable/Enable friendly fire for owned pets.
	FriendlyFire = false
	#Blacklist for pet you should't be able to give armor to. Pets from mods, which have custom armor should be included here.
	"Pet Blacklist" = []
	#Treat pet blacklist as whitelist
	"Pet Whitelist" = false
	#Increase difficulty with time
	#Here untill its back as a gamerule
	"Difficulty toggle" = true
	#How the difficulty at a position is calculated. Supported values are: 
	#GLOBAL: Serverwide difficulty value
	#PLAYERMAX: Maximum difficulty of players in a 256 radius around the position
	#PLAYERMEAN: Average difficulty of players in a 256 radius around the position
	#Allowed Values: GLOBAL, PLAYERMAX, PLAYERMEAN
	"Difficulty type" = "PLAYERMEAN"

#Black/Whitelist for various stuff
[list]
	#Entities added here will be blacklisted from their assigned flags. Usage:
	#<entity registry name> or <namespace> followed by any of:
	#[ALL,ATTRIBUTES,ARMOR,HELDITEMS,BLOCKBREAK,USEITEM,LADDER,STEAL,GUARDIAN,PARROT,TARGETVILLAGER,NEUTRALAGGRO,REVERSE].
	#Having no flags is equal to ALL. Use REVERSE to reverse all flags. Some flags do nothing for certain mobs!
	#Examples:
	#minecraft:sheep is equal to minecraft:sheep|ALL and excludes sheeps from all modifications
	#minecraft:sheep|REVERSE|ATTRIBUTES will add sheep to attributes modification only
	#minecraft:sheep|ATTRIBUTES will add sheep to everything except attributes
	"More Entities" = ["blue_skies:summoner", "blue_skies:alchemist", "blue_skies:starlit_crusher", "blue_skies:arachnarch", "alexsmobs:froststalker", "alexsmobs:centipede_tail", "ars_nouveau:wixie", "alexsmobs:snow_leopard", "alexsmobs:lobster", "theabyss:laro_fish", "mowziesmobs:lantern", "alexsmobs:seagull", "aquaculture:pink_salmon", "aquaculture:atlantic_herring", "betteranimalsplus:octopus", "alexsmobs:moose", "alexsmobs:seal", "minecraft:glow_squid", "alexsmobs:shoebill", "alexsmobs:roadrunner", "alexsmobs:laviathan", "minecraft:trader_llama", "ars_nouveau:familiar_wixie", "ars_nouveau:vexing_weald_walker", "blue_skies:supporter_pet", "goblintraders:goblin_trader", "alexsmobs:endergrade", "minecraft:horse", "youre_seeing_dungeons:seed_gloomy_ruins", "aquaculture:muskellunge", "blue_skies:jelly_drifter", "aquaculture:bayad", "betteranimalsplus:bobbit_worm", "minecraft:llama", "twilightforest:raven", "aquaculture:bluegill", "alexsmobs:maned_wolf", "youre_seeing_dungeons:despair_boss_seed", "betteranimalsplus:nautilus", "minecraft:dolphin", "nourished_end:radjelly", "betteranimalsplus:flying_fish", "stalwart_dungeons:spore_projectile", "alexsmobs:gelada_monkey", "theabyss:ralu_fish", "ars_elemental:firenando_entity", "alexsmobs:komodo_dragon", "blue_skies:azulfo", "minecolonies:mercenary", "alexsmobs:hammerhead_shark", "blue_skies:reindeer", "minecraft:donkey", "alexsmobs:tiger", "twilightforest:loyal_zombie", "betteranimalsplus:eel_freshwater", "theabyss:luro_fish", "alexsmobs:grizzly_bear", "blue_skies:firefly", "quark:stoneling", "ars_nouveau:dummy", "minecraft:bee", "aquaculture:perch", "alexsmobs:devils_hole_pupfish", "goblintraders:vein_goblin_trader", "quark:toretoise", "alexsmobs:crocodile", "guardvillagers:guard", "betteranimalsplus:moose", "youre_seeing_dungeons:divina_guardian", "quark:frog", "aquaculture:jellyfish", "undergarden:brute", "minecraft:mooshroom", "alexsmobs:frilled_shark", "alexsmobs:bison", "minecraft:villager", "aquaculture:tuna", "alexsmobs:bald_eagle", "blue_skies:snow_owl", "betteranimalsplus:eel_saltwater", "minecraft:axolotl", "stalwart_dungeons:nether_keeper", "botania:doppleganger", "alexsmobs:blobfish", "betteranimalsplus:turkey", "alexsmobs:gorilla", "aquaculture:blackfish", "undergarden:gloomper", "aquaculture:arapaima", "alexsmobs:tusklin", "minecraft:strider", "undergarden:gwibling", "minecraft:parrot", "quark:crab", "betteranimalsplus:feralwolf", "alexsmobs:cosmic_cod", "ars_nouveau:drygmy", "nourished_end:flarebug", "minecraft:wandering_trader", "aquaculture:carp", "aquaculture:pacific_halibut", "ars_nouveau:familiar_bookwyrm", "betteranimalsplus:piranha", "minecraft:iron_golem", "alexsmobs:kangaroo", "blue_skies:grittle_flatfish", "twilightforest:deer", "betteranimalsplus:barracuda", "botania:pixie", "mowziesmobs:barakoan_player", "betteranimalsplus:squirrel", "betteranimalsplus:coyote", "youre_seeing_dungeons:heaven_seed", "alexsmobs:mimic_octopus", "aquaculture:boulti", "alexsmobs:hummingbird", "alexsmobs:bunfungus", "betteranimalsplus:dragonfly", "twilightforest:squirrel", "betteranimalsplus:songbird", "minecraft:mule", "betteranimalsplus:pheasant", "alexsmobs:crow", "alexsmobs:flying_fish", "aquaculture:atlantic_cod", "betteranimalsplus:blackbear", "betteranimalsplus:jellyfish", "alexsmobs:centipede_body", "aquaculture:synodontis", "twilightforest:boar", "minecraft:pufferfish", "aquaculture:starshell_turtle", "alexsmobs:tarantula_hawk", "ars_nouveau:blazing_weald_walker", "twilightforest:dwarf_rabbit", "minecraft:fox", "aquaculture:smallmouth_bass", "betteranimalsplus:lammergeier", "alexsmobs:cachalot_whale", "snowpig:snow_pig", "mekanism:robit", "youre_seeing_dungeons:desert_pillager_patrol", "alexsmobs:warped_toad", "minecraft:chicken", "alexsmobs:giant_squid", "betteranimalsplus:whale", "ars_elemental:firenando_familiar", "blue_skies:horizofin_tunid", "nethers_exoticism:moloch", "ars_nouveau:familiar_whirlisprig", "alexsmobs:emu", "ars_elemental:flashing_weald_walker", "alexsmobs:cockroach", "aquaculture:minnow", "blue_skies:frost_spirit", "aquaculture:tambaqui", "ars_elemental:siren_entity", "betteranimalsplus:goose", "alexsmobs:flutter", "blue_skies:municipal_monkfish", "aquaculture:catfish", "mowziesmobs:barakoa_sunblocker_player", "ars_nouveau:cascading_weald_walker", "alexsmobs:terrapin", "alexsmobs:capuchin_monkey", "youre_seeing_dungeons:fiery_orb", "aquaculture:brown_shrooma", "alexsmobs:anaconda", "blue_skies:shade_monitor", "minecraft:polar_bear", "youre_seeing_dungeons:seed_heaven_boss", "mowziesmobs:grottol", "aquaculture:brown_trout", "minecraft:pig", "minecraft:turtle", "blue_skies:crogre", "aquaculture:red_shrooma", "alexsmobs:alligator_snapping_turtle", "minecraft:sheep", "aquaculture:atlantic_halibut", "betteranimalsplus:butterfly", "mowziesmobs:baby_foliaath", "youre_seeing_dungeons:despair_structure_seed", "minecraft:goat", "alexsmobs:rattlesnake", "betteranimalsplus:brownbear", "farmingforblockheads:merchant", "minecraft:cod", "aquaculture:gar", "betteranimalsplus:squid_giant", "aquaculture:red_grouper", "alexsmobs:mantis_shrimp", "ars_nouveau:familiar_starbuncle", "minecolonies:visitor", "nourished_end:ringling", "ars_elemental:siren_familiar", "alexsmobs:raccoon", "ars_nouveau:starbuncle", "blue_skies:cosmic_fox", "minecolonies:citizen", "alexsmobs:platypus", "minecraft:squid", "theabyss:lizard", "minecraft:skeleton_horse", "twilightforest:tiny_bird", "betteranimalsplus:walrus", "minecraft:cow", "undergarden:dweller", "aquaculture:rainbow_trout", "alexsmobs:fly", "ars_nouveau:familiar_drygmy", "ars_nouveau:whirlisprig", "quark:shiba", "theabyss:abylager", "blue_skies:charscale_moki", "alexsmobs:toucan", "minecraft:salmon", "alexsmobs:sea_bear", "undergarden:scintling", "twilightforest:quest_ram", "minecraft:snow_golem", "ars_nouveau:flourishing_weald_walker", "alexsmobs:anteater", "supplementaries:red_merchant", "minecraft:rabbit", "nourished_end:caster", "betteranimalsplus:deer", "aquaculture:piranha", "aquaculture:box_turtle", "alexsmobs:orca", "alexsmobs:leafcutter_ant", "ars_elemental:summon_direwolf", "twilightforest:bighorn_sheep", "alexsmobs:mungus", "alexsmobs:jerboa", "minecraft:bat", "alexsmobs:spectre", "alexsmobs:cosmaw", "ars_nouveau:summon_horse", "betteranimalsplus:crab", "betteranimalsplus:horseshoecrab", "alexsmobs:catfish", "youre_seeing_dungeons:emanciated_creature_tameable", "aquaculture:pollock", "alexsmobs:comb_jelly", "dragonmounts:dragon", "ars_elemental:summon_skelehorse", "blue_skies:sliv", "aquaculture:arrau_turtle", "alexsmobs:elephant", "aquaculture:capitaine", "alexsmobs:gazelle", "youre_seeing_dungeons:supreme_ender_eye", "ars_nouveau:bookwyrm", "minecraft:zombie_horse", "alexsmobs:sunbird", "blue_skies:stardust_ram", "alexsmobs:tasmanian_devil", "minecraft:cat", "alexsmobs:stradpole", "ars_nouveau:amethyst_golem", "blue_skies:gatekeeper", "blue_skies:crystal_camel", "ars_nouveau:summon_wolf", "minecraft:tropical_fish", "undergarden:minion", "bygonenether:wither_skeleton_horse", "minecraft:ocelot", "twilightforest:penguin", "theabyss:summoned_seeker", "betteranimalsplus:squid_colossal", "minecraft:wolf", "betteranimalsplus:reindeer", "youre_seeing_dungeons:summoned_horned_skeleton", "minecraft:panda", "undergarden:mog", "youre_seeing_dungeons:gloomy_boss_seed"]
	#Any of the following 
	#[ATTRIBUTES, ARMOR, HELDITEMS, BLOCKBREAK, USEITEM, LADDER, STEAL, GUARDIAN, PARROT, TARGETVILLAGER, NEUTRALAGGRO]
	#added here will disable that feature.
	#E.g. ["GUARDIAN"] will disable the guardian feature
	"Flag Blacklist" = []
	#Treat ATTRIBUTES flags as whitelist
	"Attribute Whitelist" = false
	#Treat ARMOR flags as whitelist
	"Armor Equip Whitelist" = false
	#Treat HELDITEMS flags as whitelist
	"Held Equip Whitelist" = false
	#Treat BLOCKBREAK flags as whitelist
	"Breaker Whitelist" = false
	#Treat USEITEM flags as whitelist
	"Item Use Whitelist" = false
	#Treat LADDER flags as whitelist
	"Ladder Whitelist" = false
	#Treat STEAL flags as whitelist
	"Steal Whitelist" = false
	#Treat GUARDIAN flags as whitelist
	"Guardian Whitelist" = false
	#Treat PARROT flags as whitelist
	"Parrot Whitelist" = false
	#Treat TARGETVILLAGER flags as whitelist
	"Villager Whitelist" = false
	#Treat NEUTRALAGGRO flags as whitelist
	"Neutral Aggro Whitelist" = false

#Debugging
[debug]
	#Enable showing of entity paths
	"Path Debugging" = false

#Settings for mod integration
[integration]
	#Should the scaling health mods difficulty system be used instead of this ones. (Requires scaling health mod)
	"Use Scaling Health Mod" = false

#Settings regarding custom ai for mobs
[ai]
	#Whitelist for blocks, which can be actively broken. 
	#Usage: <registry name;classname;tag;namespace> put "!" infront to exclude blocks
	#Note: If you include common blocks (like grass blocks) the pathfinding will be a bit strange
	"Block Whitelist" = ["forge:glass", "forge:glass_panes", "minecraft:fence_gates", "forge:fence_gates", "minecraft:wooden_doors"]
	#Treat Block Whitelist as Blocklist
	"Block as Blacklist" = false
	#Use the block breaking sound instead of a knocking sound
	Sound = false
	#Chance for a mob to be able to break blocks
	#Range: 0.0 ~ 1.0
	"Breaker Chance" = 0.3
	#Initial cooldown for block breaking mobs
	#Range: > 0
	"Breaker Initial Cooldown" = 120
	#Cooldown for breaking blocks
	#Range: > 0
	"Breaker Cooldown" = 20
	#Chance for a mob to be able to steal items
	#Range: 0.0 ~ 1.0
	"Stealer Chance" = 0.0
	#Items which will be given to mobs who can break blocks. Empty list = no items. Syntax: id;weight
	"Breaking items" = ["minecraft:diamond_pickaxe;1", "minecraft:iron_axe;2"]
	#Should mobs be able to break tile entities? Evaluated before the break list
	"Break Tiles" = true
	#Chance for neutral mobs to be aggressive
	#Range: 0.0 ~ 1.0
	"Neutral Aggressive Chance" = 0.2
	#List for of pairs containing which mobs auto target others. Syntax is [mob id]-[mob id] where second value is the target.
	# e.g. minecraft:zombie-minecraft:skeleton makes all zombies target skeletons
	"Auto Target List" = []
	#Difficulty at which mobs are able to break blocks
	#Range: 0.0 ~ 1.7976931348623157E308
	"Difficulty Break AI" = 0.0
	#Difficulty at which mobs are able to steal items
	#Range: 0.0 ~ 1.7976931348623157E308
	"Difficulty Steal AI" = 0.0
	#Chance for mobs to be able to ride a guardian
	#Range: 0.0 ~ 1.0
	"Guardian Chance" = 1.0
	#Chance for mobs to be able to ride a parrot
	#Range: 0.0 ~ 1.0
	"Fly Chance" = 0.5

#Configs regarding mobs spawning with equipment
[equipment]
	#Blacklist for mods. Add modid to prevent items from that mod being equipped. (For individual items use the equipment.json)
	"Item Blacklist" = []
	#Use blacklist as whitelist
	"Item Whitelist" = false
	#Blacklist for items mobs should never be able to use.
	#Use as in using the item similar to players (e.g. shooting bows)
	"Item Use Blacklist" = ["bigbrain:buckler"]
	#Turn the use blacklist into a whitelist
	"Item Use Whitelist" = false
	#Blacklist for specific mobs and items they shouldnt use (e.g. skeletons already use bows)
	#<entity registry name-item>
	#For different items but same entity use multiple lines
	#Some special names are BOW, TRIDEN, CROSSBOW refering to every bow/trident/crossbow item (So you dont need to type e.g. every bow item)
	"Entity Item Use Blacklist" = ["minecraft:drowned;TRIDENT", "minecraft:illusioner;BOW", "minecraft:piglin;CROSSBOW", "minecraft:pillager;CROSSBOW", "minecraft:skeleton;BOW", "minecraft:snow_golem;minecraft:snowball", "minecraft:stray;BOW", "minecraft:wither_skeleton;BOW"]
	#Base chance that a mob can have one piece of armor
	#Range: 0.0 ~ 1.0
	"Equipment Chance" = 1.0
	#Base chance for each additional armor pieces
	#Range: 0.0 ~ 1.0
	"Additional Equipment Chance" = 0.5
	#Adds additional x*difficulty% to base equip chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Equipment Addition" = 0.5
	#Chance for mobs to have a weapon
	#Range: 0.0 ~ 1.0
	"Weapon Chance" = 0.25
	#Adds additional x*difficulty% to base weapon chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Weapon Chance Add" = 0.5
	#Base chance for each armor pieces to get enchanted
	#Range: 0.0 ~ 1.0
	"Enchanting Chance" = 0.5
	#Adds additional x*difficulty% to base enchanting chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Enchanting Addition" = 0.5
	#Specify min and max enchanting levels according to difficulty. difficulty-minLevel-maxLevel
	"Enchanting Calc" = ["0-5-10", "25-5-15", "50-10-17", "100-15-25", "200-20-30", "250-30-35"]
	#Chance for mobs to have an item in offhand
	#Range: 0.0 ~ 1.0
	"Item Equip Chance" = 0.05
	#Adds additional x*difficulty% to base item chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Item Chance add" = 0.5
	#Should mobs drop the armor equipped through this mod? (Other methods e.g. through vanilla is not included)
	"Should drop equipment" = false

#Settings for attribute modifiers
[attributes]
	#Health will be multiplied by difficulty*0.016*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Health Increase Multiplier" = 1.797
	#Health will be multiplied by at maximum this. Set to 0 means no limit
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Health Increase" = 0.0
	#Round health to the nearest x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Round HP" = 0.0
	#Damage will be multiplied by difficulty*0.008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Damage Increase Multiplier" = 1.797
	#Damage will be multiplied by at maximum this. Set to 0 means no limit
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Damage Increase" = 0.0
	#Speed will be increased by difficulty*0.0008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Speed Increase" = 1.0
	#Maximum increase in speed
	#Range: 0.0 ~ 1.0
	"Max Speed" = 0.1
	#Knockback will be increased by difficulty*0.002*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Knockback Increase" = 1.0
	#Maximum increase in knockback
	#Range: 0.0 ~ 1.0
	"Max Knockback" = 0.5
	#Magic resistance will be increased by difficulty*0.0016*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Magic Resistance Increase" = 1.0
	#Maximum increase in magic resistance. Magic reduction is percentage
	#Range: 0.0 ~ 1.0
	"Max Magic Resistance" = 0.75
	#Projectile Damage will be multiplied by 1+difficulty*0.008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Projectile Damage Increase" = 1.797
	#Projectile damage will be multiplied by maximum of this
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Projectile Damage" = 0.0

