// priority: 0

console.info('KubeJS - Loading Whimsyhell Custom Events')

ServerEvents.recipes(event => {
    // Remove recipes
    event.remove([
        { output: 'kubejs:dummy_fluid_item' },
        { output: 'alexsmobs:roadrunner_boots' },
        { output: 'alexsmobs:crocodile_chestplate' },
        { output: 'alexsmobs:centipede_leggings' },
        { output: 'alexsmobs:frontier_cap' },
        { output: 'alexsmobs:froststalker_helmet' },
        { output: 'alexsmobs:pigshoes' },
        { output: 'alexsmobs:straddle_helmet' },
        { output: 'alexsmobs:emu_leggings' },
        { output: 'alexsmobs:rocky_chestplate' },
        { output: 'alexsmobs:novelty_hat' },
        { output: 'quark:forgotten_hat' },
        { output: 'cataclysm:ignitium_helmet' },
        { output: 'cataclysm:ignitium_chestplate' },
        { output: 'cataclysm:ignitium_elytra_chestplate' },
        { output: 'cataclysm:ignitium_leggings' },
        { output: 'cataclysm:ignitium_boots' },
        { output: 'cataclysm:monstrous_helm' },
        { output: 'theoneprobe:probe' },
        { output: 'theoneprobe:creativeprobe' },
        { output: 'theoneprobe:probenote' },
        { output: 'theoneprobe:diamond_helmet_probe' },
        { output: 'theoneprobe:gold_helmet_probe' },
        { output: 'theoneprobe:iron_helmet_probe' },
        { output: 'piglin_expansion:piglin_divinity_gem' },
        { output: 'piglin_expansion:piglin_divinity_essence' },
        { output: 'piglin_expansion:divinity_netherite_ingot' },
        { output: 'piglin_expansion:divinity_netherite_armor_helmet' },
        { output: 'piglin_expansion:divinity_netherite_armor_chestplate' },
        { output: 'piglin_expansion:divinity_netherite_armor_leggings' },
        { output: 'piglin_expansion:divinity_netherite_armor_boots' },
        { output: 'piglin_expansion:piglin_divinity_staff' },
        { output: 'bygonenether:gilded_netherite_helmet' },
        { output: 'bygonenether:gilded_netherite_chestplate' },
        { output: 'bygonenether:gilded_netherite_leggings' },
        { output: 'bygonenether:gilded_netherite_boots' },
        { output: 'mysticalagriculture:inferium_sword' },
        { output: 'mysticalagriculture:inferium_pickaxe' },
        { output: 'mysticalagriculture:inferium_shovel' },
        { output: 'mysticalagriculture:inferium_axe' },
        { output: 'mysticalagriculture:inferium_staff' },
        { output: 'mysticalagriculture:inferium_crossbow' },
        { output: 'mysticalagriculture:inferium_bow' },
        { output: 'mysticalagriculture:inferium_scythe' },
        { output: 'mysticalagriculture:inferium_sickle' },
        { output: 'mysticalagriculture:inferium_helmet' },
        { output: 'mysticalagriculture:inferium_chestplate' },
        { output: 'mysticalagriculture:inferium_leggings' },
        { output: 'mysticalagriculture:inferium_boots' },
        { output: 'mysticalagriculture:prudentium_sword' },
        { output: 'mysticalagriculture:prudentium_pickaxe' },
        { output: 'mysticalagriculture:prudentium_shovel' },
        { output: 'mysticalagriculture:prudentium_axe' },
        { output: 'mysticalagriculture:prudentium_staff' },
        { output: 'mysticalagriculture:prudentium_crossbow' },
        { output: 'mysticalagriculture:prudentium_bow' },
        { output: 'mysticalagriculture:prudentium_scythe' },
        { output: 'mysticalagriculture:prudentium_sickle' },
        { output: 'mysticalagriculture:prudentium_helmet' },
        { output: 'mysticalagriculture:prudentium_chestplate' },
        { output: 'mysticalagriculture:prudentium_leggings' },
        { output: 'mysticalagriculture:prudentium_boots' },
        { output: 'mysticalagriculture:tertium_sword' },
        { output: 'mysticalagriculture:tertium_pickaxe' },
        { output: 'mysticalagriculture:tertium_shovel' },
        { output: 'mysticalagriculture:tertium_axe' },
        { output: 'mysticalagriculture:tertium_staff' },
        { output: 'mysticalagriculture:tertium_crossbow' },
        { output: 'mysticalagriculture:tertium_bow' },
        { output: 'mysticalagriculture:tertium_scythe' },
        { output: 'mysticalagriculture:tertium_sickle' },
        { output: 'mysticalagriculture:tertium_helmet' },
        { output: 'mysticalagriculture:tertium_chestplate' },
        { output: 'mysticalagriculture:tertium_leggings' },
        { output: 'mysticalagriculture:tertium_boots' },
        { output: 'mysticalagriculture:imperium_sword' },
        { output: 'mysticalagriculture:imperium_pickaxe' },
        { output: 'mysticalagriculture:imperium_shovel' },
        { output: 'mysticalagriculture:imperium_axe' },
        { output: 'mysticalagriculture:imperium_staff' },
        { output: 'mysticalagriculture:imperium_crossbow' },
        { output: 'mysticalagriculture:imperium_bow' },
        { output: 'mysticalagriculture:imperium_scythe' },
        { output: 'mysticalagriculture:imperium_sickle' },
        { output: 'mysticalagriculture:imperium_helmet' },
        { output: 'mysticalagriculture:imperium_chestplate' },
        { output: 'mysticalagriculture:imperium_leggings' },
        { output: 'mysticalagriculture:imperium_boots' },
        { output: 'mysticalagriculture:supremium_sword' },
        { output: 'mysticalagriculture:supremium_pickaxe' },
        { output: 'mysticalagriculture:supremium_shovel' },
        { output: 'mysticalagriculture:supremium_axe' },
        { output: 'mysticalagriculture:supremium_staff' },
        { output: 'mysticalagriculture:supremium_crossbow' },
        { output: 'mysticalagriculture:supremium_bow' },
        { output: 'mysticalagriculture:supremium_scythe' },
        { output: 'mysticalagriculture:supremium_sickle' },
        { output: 'mysticalagriculture:supremium_helmet' },
        { output: 'mysticalagriculture:supremium_chestplate' },
        { output: 'mysticalagriculture:supremium_leggings' },
        { output: 'mysticalagriculture:supremium_boots' },
        { output: 'mysticalagriculture:awakened_supremium_sword' },
        { output: 'mysticalagriculture:awakened_supremium_pickaxe' },
        { output: 'mysticalagriculture:awakened_supremium_shovel' },
        { output: 'mysticalagriculture:awakened_supremium_axe' },
        { output: 'mysticalagriculture:awakened_supremium_staff' },
        { output: 'mysticalagriculture:awakened_supremium_bow' },
        { output: 'mysticalagriculture:awakened_supremium_scythe' },
        { output: 'mysticalagriculture:awakened_supremium_sickle' },
        { output: 'mysticalagriculture:awakened_supremium_crossbow' },
        { output: 'mysticalagriculture:awakened_supremium_helmet' },
        { output: 'mysticalagriculture:awakened_supremium_chestplate' },
        { output: 'mysticalagriculture:awakened_supremium_leggings' },
        { output: 'mysticalagriculture:awakened_supremium_boots' },
        { output: 'mysticalagriculture:unattuned_augment' },
        { output: 'mysticalagriculture:absorption_i_augment' },
        { output: 'mysticalagriculture:health_boost_i_augment' },
        { output: 'mysticalagriculture:pathing_aoe_i_augment' },
        { output: 'mysticalagriculture:night_vision_augment' },
        { output: 'mysticalagriculture:water_breathing_augment' },
        { output: 'mysticalagriculture:absorption_ii_augment' },
        { output: 'mysticalagriculture:jump_boost_i_augment' },
        { output: 'mysticalagriculture:health_boost_ii_augment' },
        { output: 'mysticalagriculture:speed_i_augment' },
        { output: 'mysticalagriculture:mining_aoe_i_augment' },
        { output: 'mysticalagriculture:tilling_aoe_i_augment' },
        { output: 'mysticalagriculture:pathing_aoe_ii_augment' },
        { output: 'mysticalagriculture:absorption_iii_augment' },
        { output: 'mysticalagriculture:fire_resistance_augment' },
        { output: 'mysticalagriculture:jump_boost_ii_augment' },
        { output: 'mysticalagriculture:step_assist_augment' },
        { output: 'mysticalagriculture:health_boost_iii_augment' },
        { output: 'mysticalagriculture:strength_i_augment' },
        { output: 'mysticalagriculture:speed_ii_augment' },
        { output: 'mysticalagriculture:no_fall_damage_augment' },
        { output: 'mysticalagriculture:mining_aoe_ii_augment' },
        { output: 'mysticalagriculture:attack_aoe_i_augment' },
        { output: 'mysticalagriculture:tilling_aoe_ii_augment' },
        { output: 'mysticalagriculture:pathing_aoe_iii_augment' },
        { output: 'mysticalagriculture:absorption_iv_augment' },
        { output: 'mysticalagriculture:poison_resistance_augment' },
        { output: 'mysticalagriculture:jump_boost_iii_augment' },
        { output: 'mysticalagriculture:health_boost_iv_augment' },
        { output: 'mysticalagriculture:strength_ii_augment' },
        { output: 'mysticalagriculture:speed_iii_augment' },
        { output: 'mysticalagriculture:mining_aoe_iii_augment' },
        { output: 'mysticalagriculture:attack_aoe_ii_augment' },
        { output: 'mysticalagriculture:tilling_aoe_iii_augment' },
        { output: 'mysticalagriculture:pathing_aoe_iv_augment' },
        { output: 'mysticalagriculture:mining_fatigue_resistance_augment' },
        { output: 'mysticalagriculture:absorption_v_augment' },
        { output: 'mysticalagriculture:wither_resistance_augment' },
        { output: 'mysticalagriculture:health_boost_v_augment' },
        { output: 'mysticalagriculture:strength_iii_augment' },
        { output: 'mysticalagriculture:flight_augment' },
        { output: 'mysticalagriculture:mining_aoe_iv_augment' },
        { output: 'mysticalagriculture:attack_aoe_iii_augment' },
        { output: 'mysticalagriculture:tilling_aoe_iv_augment' },
        { output: 'mysticalagradditions:inferium_paxel' },
        { output: 'mysticalagradditions:prudentium_paxel' },
        { output: 'mysticalagradditions:tertium_paxel' },
        { output: 'mysticalagradditions:imperium_paxel' },
        { output: 'mysticalagradditions:supremium_paxel' },
        { output: 'mysticalagradditions:awakened_supremium_paxel' },
        { output: 'mysticalagradditions:inferium_paxel' }
    ])

    // event.recipes.create.pressing(output[], input)
    event.recipes.create.pressing('mysticalagradditions:dragon_scale','forbidden_arcanus:dragon_scale')

    // event.recipes.create.mixing(output[], input[])
    // event.recipes.create.mixing(output[], input[]).heated()
    // event.recipes.create.mixing(output[], input[]).superheated()
    event.recipes.create.mixing('whimsyhell:whimsy_ingot', ['whimsyhell:whimsy_dust', 'mysticalagriculture:awakened_supremium_ingot']).superheated()


    // event.shaped(Item.of('output', <output count>), [<shape>],{<shape_mappings>})
    event.shaped(
        Item.of('whimsyhell:whimsy_sword', 1),
        [
            'WWW',
            'MFW',
            'AMW'
        ],
        {
            A: 'theabyss:abyss_sword',
            F: 'forbidden_arcanus:eternal_stella',
            M: 'mysticalagradditions:nether_star_crux',
            W: 'whimsyhell:whimsy_ingot'
        }
    )
})
