//priority: 1

settings.logAddedRecipes = true
settings.logRemovedRecipes = true
settings.logSkippedRecipes = false
settings.logErroringRecipes = true

console.info('Whimsyhell Tags Loaded')

onEvent('item.tags', event => {
    // Lycanite tag for use by Create crusher for crushed lycanite
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_afritlung')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_apollyonclaw')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_argustail')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_astarothclaw')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_bansheeeye')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_behemophethand')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_belphegorarm')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_bruchaquill')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_cherufecore')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_cinderblade')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_clinkscythe')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_conbabutt')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_darklingskull')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_eechetikarm')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_entarm')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_epionwing')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_erepededrill')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_ettinclub')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_eyewigeye')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_frostweaverleg')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_gammasphere')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_geonachfist')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_geonachspear')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_goldscepterhead')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_grueclaw')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_ioraystinger')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_ironaxehead')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_ironguard')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_ironpaxel')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_ironpikejoint')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_ironrod')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_lacedonhead')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_malwratheye')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_naxiriseye')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_raidrablade')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_reaperclaw')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_remobrawing')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_serpixmandible')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_spectretendril')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_sprigganheart')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_sprigganroot')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_stryderheart')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_sutiramustinger')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_sylphwing')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_uvaraptorskull')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_vapulacrystal')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_ventoraptorskull')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_vespidstinger')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_wargskull')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_wendigoantler')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_wildkinarm')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_woodenguard')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_woodenpaxel')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_woodenrod')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_wraithskull')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_xaphanspine')
    event.add('kubejs:lycanite_tag', 'lycanitesmobs:equipmentpart_zephyrcloud')
    
    // Whimsy Ingot and Whimsy Plate tag used to crush back to Whimsy Dust
    event.add('kubejs:whimsy_ingot_plate_tag', 'kubejs:whimsy_ingot')
    event.add('kubejs:whimsy_ingot_plate_tag', 'kubejs:whimsy_plate')
})